### ISSUE TITLE
webpack打包一直出错

### ISSUE THREAD

**Issue by tyuexingzhe** [chenshenhai/koa2-note#10]
我就是把您的项目下载下来，利用快速启动npm run start_static进行打包，这是第一次出的问题
<img width="634" alt="1" src="https://cloud.githubusercontent.com/assets/13444993/26281516/e3e7544c-3e2b-11e7-9dd7-e1afcc50dd97.png">
在网上查是需要开启presets: ['es2015', 'react']，但是看您的项目里给注释掉了，
<img width="640" alt="3" src="https://cloud.githubusercontent.com/assets/13444993/26281525/157a956e-3e2c-11e7-99ad-93db6360dcc4.png">
我给取消了注释，然后又报了类似的错误，但是位置不同了
<img width="634" alt="2" src="https://cloud.githubusercontent.com/assets/13444993/26281527/23cab3e2-3e2c-11e7-8331-0d29591ec109.png">

请问这个问题出在哪里呢？我的node版本是7.10.0，npm版本是4.5.0

**Comment by chenshenhai** [comment]
@tyuexingzhe 您好！在项目里面有个`.babelrc`文件，你应该是忘记引入了

**Comment by tyuexingzhe** [comment]
恩恩，是这个原因~
