### ISSUE TITLE
koa-router跟着你路径还是爆404 

### ISSUE THREAD

**Issue by Foreverofh** [chenshenhai/koa2-note#11]
![image](https://cloud.githubusercontent.com/assets/15324717/26540388/db8f66d2-4483-11e7-95d6-0b2357b8649e.png)
![image](https://cloud.githubusercontent.com/assets/15324717/26540409/f5bc3b70-4483-11e7-8ed5-94e11ae29926.png)
![image](https://cloud.githubusercontent.com/assets/15324717/26540418/00de8d5a-4484-11e7-9711-b1eb27feac2a.png)

**Comment by chenshenhai** [comment]
@Foreverofh 您好，我知道你的问题了，你第一张截图里面的父路由是 `/`，第二章截图里面的子路由是`/login`，结合起来访问应该是 `http://127.0.0.1:3000//login`，也就是路径`//login`，如果你只是想访问`/login`，那么就修改去掉父路由或者子路由的其中一个`/`

**Comment by Foreverofh** [comment]
@chenshenhai  谢谢你啊.因为刚学node没多久,之前看了下express路由.以为和express路由一样这样写都可以.还有我想问下为什么数据库选mysql,而不是mongodb? 因为我知道mongodb不能回滚真的很坑爹,中间操作报错数据已经插入到数据库,你是怎么解决这个问题. 我想问下实际工作中用什么数据库?

**Comment by chenshenhai** [comment]
@Foreverofh 我选择MySQL主要是比较熟悉，而且MySQL5.7支持了json类型，对比之前复杂数据存储例如json类型，就采用mongodb是比较合适，但是现在MySQL5.7都支持了json类型和相关json类型的数据操作，用起来也比较符合以前的习惯，所以就一直使用MySQL。

其实用什么数据库都不需要太纠结，根据实际情况，要解决什么问题就选择什么低成本方案，技术选型这一块我一直感觉应该是“简单可以用，用的开心就好”O(∩_∩)O~

**Comment by Foreverofh** [comment]
哦哦,还是觉定用mysql好. 推荐一下学习mysql方法吗?

**Comment by chenshenhai** [comment]
@Foreverofh 你可以用`nodejs + mysql`开始学习
- 第一阶段：用`npm`的`mysql`模块直接拼接`sql`语句操作数据库
- 第二阶段：拼接`sql`语句连表操作，多表视图操作
- 第三阶段：自己学会过滤`sql`中的注入问题
- 第四阶段：抛弃sql语句拼接，选择用合适安全高度封装的mysql操作库，提高开发效率，例如`sequelize`

**Comment by Foreverofh** [comment]
@chenshenhai  好的 谢谢!
