### ISSUE TITLE
大神，这里的data，没有看明白，麻烦讲解下

### ISSUE THREAD

**Issue by kg-web** [chenshenhai/koa2-note#13]
![image](https://user-images.githubusercontent.com/20922287/27538169-528982f0-5aa9-11e7-913c-bdb6a293424c.png)

**Comment by gwl002** [comment]
监听req
req中有数据来就会响应

**Comment by gwl002** [comment]
这个pro还只能算初级吧。

**Comment by chenshenhai** [comment]
@kg-web 您好！你在截图里所指的`data`是监听的回调传入的参数，`ctx.req`封装的是原生的nodejs request对象，具体文档在这里 https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by kg-web** [comment]
好的，谢谢

**Comment by kg-web** [comment]
@gwl002 什么初级
