### ISSUE TITLE
关于接口访问为啥请求两次?

### ISSUE THREAD

**Issue by Foreverofh** [chenshenhai/koa2-note#14]
![to2uree7 q84mjm12qv7dt](https://user-images.githubusercontent.com/15324717/28028608-a6b7740a-65cf-11e7-891c-590731da1d72.png)

**Comment by chenshenhai** [comment]
@Foreverofh 您好，截图信息太少了o(╯□╰)o，看不出问题，麻烦你贴出完整的代码，我好排查你的问题

**Comment by Foreverofh** [comment]
我跟着你封装下router,之后访问http://localhost:3000/;我在接口打印console.log(111);会打印2次,这个是什么问题!!!

**Comment by Foreverofh** [comment]
![image](https://user-images.githubusercontent.com/15324717/28177554-bfd41122-682d-11e7-96f2-5f9bdbfd4585.png)

**Comment by chenshenhai** [comment]
@Foreverofh 您好，麻烦把你出问题代码贴出来看看，还有`console.log`在哪里打的日志也指出来，单纯说按照文章来做，我是分析不出原因的  o(╯□╰)o

**Comment by lancerfox** [comment]
因为请求页面的时候结束，还请求了一个网页标题ico图标，所以就请求了两次。

**Comment by chenshenhai** [comment]
@lancerfox 有这种可能， @Foreverofh 你可以把`ctx.url`打印出来看看就知道是哪个请求了
