### ISSUE TITLE
开发debug

### ISSUE THREAD

**Issue by Pzhicong** [chenshenhai/koa2-note#20]
按照你的文档，执行命令后并没有出现chrome调试的链接，是跟系统有关么，我的是windows，64位，默认谷歌浏览器
![_20170814105254](https://user-images.githubusercontent.com/13126996/29256655-a139299a-80de-11e7-9a7c-637a3742c573.png)

**Comment by chenshenhai** [comment]
@Pzhicong 您好，请问你的node版本是多少的？

**Comment by Pzhicong** [comment]
8.3.0，最新的

**Comment by chenshenhai** [comment]
@Pzhicong 您好！不好意思，最近工作比较忙，回复比较晚。
我查看了原因，这个问题是chrome和node.js有所变化产生的，原理是没有问题，只是操作过程中会有些变化，后续会更新文档，谢谢你反馈！

**Comment by chenshenhai** [comment]
@Pzhicong 您好，已经修正了最新的debug说明，发布好了
https://chenshenhai.github.io/koa2-note/note/debug/info.html
