### ISSUE TITLE
是否还在更新中？

### ISSUE THREAD

**Issue by peterleng** [chenshenhai/koa2-note#24]
请问一下：
1，这个教程是否还在为最新版本的koa做同步更新呢？
2，ejs模版引擎的教程是否可以加入layout布局的讲解？
3，数据库操作时是否可以加入Sequelize的ORM的相关教程？
4，如何设置自己的域名，而非采用localhost的方式运行呢？

**Comment by chenshenhai** [comment]
@peterleng Hi！您好
1. 这教程还在做同步更新，只是目前Koa2的变化不大。
2. ejs官网和社区已经有很详细的教程和原理分析，我研究不深，不好意思班门弄斧o(╯□╰)o。
3. 数据库Sequelize操作这个正规划去做。
4. 设置域名你可以修改本地hosts，可以用SwitchHost这个工具
