### ISSUE TITLE
Miss end tag for li

### ISSUE THREAD

**Issue by RoamIn** [chenshenhai/koa2-note#30]
https://github.com/chenshenhai/koa2-note/blob/fab3aa64929727b1e64a69a2fdf2e5dea28039be/demo/static-server/util/dir.js#L21

So is README.md
![miss-end-tag](https://user-images.githubusercontent.com/11537595/34450872-f6dcd214-ed50-11e7-8c2c-536a344d4b52.png)

**Comment by chenshenhai** [comment]
@RoamIn Thank you!  I has fixed it!
 O(∩_∩)O
