### ISSUE TITLE
 Inappropriate encoding

### ISSUE THREAD

**Issue by fatefinger** [chenshenhai/koa2-note#32]
https://github.com/chenshenhai/koa2-note/blob/fab3aa64929727b1e64a69a2fdf2e5dea28039be/demo/project/init/util/get-sql-content-map.js#L13

Use 'utf8' instead of 'binary' to avoid garbled characters when inserting Chinese character into database here.

**Comment by chenshenhai** [comment]
@fatefinger Thank you! I have fix it
