### ISSUE TITLE
req.pipe(busboy)  : - )

### ISSUE THREAD

**Issue by fe-hunk** [chenshenhai/koa2-note#33]
https://github.com/chenshenhai/koa2-note/blob/fab3aa64929727b1e64a69a2fdf2e5dea28039be/demo/upload/util/upload.js#L90

这行怎么理解 ，有什么作用

**Comment by chenshenhai** [comment]
@fe-hunk 您好！这个`req.pipe(busboy)` 我的理解是把 `node.http.req`中的只读文件流`readable stream`数据写到`writable stream`中用于把文件流写到磁盘上
