### ISSUE TITLE
关于补充RESTFULL

### ISSUE THREAD

**Issue by mrsai** [chenshenhai/koa2-note#5]
你好，后期会不会有 restful api 的架构，包括一些验证 ，如 koa-jwt 等 。静静等待

**Comment by ChenShenhai** [comment]
@mrsai 您好，谢谢你的建议，最近在重新修订这本书，后面考虑看看要怎么排版加上去哈。

**Comment by lzm-zeem** [comment]
你好，关于mongodb的数据的持久化koa2怎么解决，
比如：express时代，用的就是connect-mongo库和express-session，那么koa2怎么办？
大神求解

**Comment by chenshenhai** [comment]
@lzm-zeem 可以使用 `sequelize` 模块进行处理持久层
