### ISSUE TITLE
断点调试会跳过的问题

### ISSUE THREAD

**Issue by lyt308012546** [chenshenhai/koa2-note#6]
在webstorm中，ansyc/await的函数在断点调试会跳过，有解决方案么？

**Comment by chenshenhai** [comment]
@lyt308012546 您好，webstrom的断点调试没怎用，webstrom的问题建议你去stackoverflow社区提问。

**Comment by jawil** [comment]
有条评论就给我发个邮件，还以为是更新了，，，路过~
