### ISSUE TITLE
路径不匹配

### ISSUE THREAD

**Issue by dk123sw** [chenshenhai/koa2-note#61]
project中  webpack 输出路径
output: {
    path: distResolve(''),
    filename: 'vendorjs/[name].js'
  },
请求路径为 http://localhost:3001/output/dist/js/vendor.js
目前项目跑起来无法加载前端js文件

**Comment by chenshenhai** [comment]
@dk123sw 您好，谢谢你提醒，这个webpack4的编译配置已经重新修改好了。
