### ISSUE TITLE
关于npm run dev 的问题需要咨询

### ISSUE THREAD

**Issue by mailylqj** [chenshenhai/koa2-note#7]
大神，按照你的demo，在package中有如下代码
"dev": "npm run dev_server & npm run dev_static",
    "dev_server": "nodemon --harmony ./server/app",
    "dev_static": "webpack --watch --config ./static/build/webpack.dev.config.js",
但是我执行npm run dev 总是能启动项目，但是不能启动webpack watch，如果交换了dev_server和dev_static的位置，又只能启动webpack watch不能启动项目！求大神指导

**Comment by chenshenhai** [comment]
@mailylqj 你好，`npm run dev_server & npm run dev_static` 这个命令在Linux、Mac下是可以直接同时执行两个命令，但是在Windows下不能这么直接执行，只能开两个命令框分别执行这两个命令。
